#! /usr/bin/bash

Check_args(){ #Tasneem
}

Replace() { #Tasneem
}

Print() { #Safa
}

Sorted() { #Tasneem
}

Max() { #Safa
}

Min() { #Safa
}

# Basel
# This Avg Function calculates the average of all of the inputs 
Avg() { 
# here we need to know how many inputs do we have
# we can use the Count Function do get that result
local count=$(Count)
local sum=$(sum)
local avg=$((sum / count))

    echo "The Average of the series is: $avg"
    return $avg
}

# Basel
# This Count Function counts the number of the elements in the series 
Count() {
    # here we create a local variable 
    local counter=0 
    # we go through the inputs array and increment the counter every lap
    for input in "${inputs[@]}"; do
        ((counter++))
    done
    echo "The Number of elements in the series: $counter"
    return $counter;
}

# Basel
# This Sum Function sums the numbers of the inputs array 
Sum() { 
    # here we create a local variable 
    local sum=0 
    # we go through the inputs array and add the value to the sum variable 
    for input in "${inputs[@]}"; do
        ((sum+=input))
    done
    echo "The Sum of the series $sum"
    return $sum;
}

PS3="Please make a selection => "
menu="Replace Print Sorted Max Min Avg Count Sum"
menuu="\n1)Replace\n2)Print\n3)Sorted\n4)Max\n5)Min\n6)Avg\n7)Count\n8)Sum\n9)Exit"
while true
do
    select action in $menu
    do
        Check_args
        case $action in
        Replace)
            Replace
        ;;
        Print)
            Print
        ;;
        Sorted)
            Sorted
        ;;
        Max)
            Max
        ;;
        Min)
            Min
        ;;
        Avg)
            Avg
        ;;
        Count)
            Count
        ;;
        Sum)
            Sum
        ;;
        Exit)
            exit
        ;;
        *) echo "ERROR: Invalid selection"
        ;;
        esac
        echo -e $menuu
    done
done
