#! /usr/bin/bash

Check_args(){ #Tasneem
    if [[ $# -ge 3 && "$@" =~ ^[0-9\ ]+$ ]]; then
        NUMS="$@"
    else
        while true; do
            read -p "Enter a Series of numbers: " nums
            echo
            read -a array <<< "$nums"
            if [[ ${#array[@]} -ge 3 && "$nums" =~ ^[0-9\ ]+$ ]]; then
                NUMS=${array[*]}
                unset array
                break
            else
                echo "Invalid input. Please enter at least 3 numbers separated by spaces."
            fi
        done
    fi
}

Replace() { #Tasneem
set -- ""
Check_args
}

Print() { #Safa
echo "$NUMS"
return 0	
}

Sort() { #Tasneem
printf "%s\n" "${NUMS[@]}" > file.txt
tr ' ' '\n' < file.txt | sort -n | tr '\n' ' '
rm file.txt
echo
}

Max() { #Safa
local max=${1}
for num in "${@:2}";do 
    if (($num>$max)); then 
        max=$num
    fi
done
echo "$max"
return $max
}

Min() { #Safa
local min=${1}
for num in "${@:2}";do 
    if (($num<$min)); then 
	min=$num
    fi
done
echo "$min"
return $min
}

# Basel
# This Count Function counts the number of the elements in the series 
Count() {
# here we create a local variable 
local counter=0 
    # we loop through the inputs array and increment the counter every lap
    for input in "${@:1}"; do
        ((counter++))
    done
    echo "$counter"
}

# Basel
# This Sum Function sums the numbers of the inputs array 
Sum() { 
# here we create a local variable 
local sum=0 
    # we loop through the inputs array and add the value to the sum variable 
    for input in "${@:1}"; do
        ((sum+=input))
    done
    echo "$sum"
}

# Basel
# This Avg Function calculates the average of all of the inputs 
Avg() { 
# here we need to know how many inputs do we have
# we can use the Count + Sum Function do get that result
local count=$(Count ${NUMS[@]})
local sum=$(Sum ${NUMS[@]})
local avg=$(echo "scale=2; $sum / $count" | bc)

# here we used echo and not return because the return cant return a decimal/float numbers
echo $avg
}

PS3="Please make a selection => "
menu="Replace Print Sort Max Min Avg Count Sum Exit"
menuu="\n1) Replace\n2) Print\n3) Sort\n4) Max\n5) Min\n6) Avg\n7) Count\n8) Sum\n9) Exit"
while true
do
    Check_args $@
    select action in $menu
    do
        echo
        case $action in
        Replace) echo "----Replacing Series---"; Replace
        ;;
        Print) echo -n "----> The Series of numbers is: " ; Print
        ;;
        Sort) echo -n "----> The Sorted Series is: "; Sort
        ;;
        Max) echo -n "----> The Maximum number is: "; Max ${NUMS[@]}
        ;;
        Min) echo -n "----> The Minimum number is: "; Min ${NUMS[@]}
        ;;
        Avg) echo -n "----> The Average of the series is: "; Avg
        ;;
        Count) echo -n "The Number of elements in the series is: "; Count ${NUMS[@]}
        ;;
        Sum) echo -n "The Sum of the series is: "; Sum ${NUMS[@]}
        ;;
        Exit) exit
        ;;
        *) echo "----> ERROR: Invalid selection"
        ;;
        esac
        echo -e $menuu
        echo
    done
done
